# playbook.yml
---
- name: Backup Odoo
  hosts: odoo_servers
  become: yes
  tasks:
    - name: Create backup directory on Odoo server
      file:
        path: "{{ odoo_backup_directory }}/{{ inventory_hostname }}"
        state: directory
        mode: '0755'

    - name: Backup Odoo database
      shell: "PGPASSWORD={{ odoo_db_pass }} pg_dumpall -h localhost -U {{ odoo_db_user }} -f {{ odoo_backup_directory }}/{{ inventory_hostname }}/postgres_backup_{{ ansible_date_time.date }}.sql"


