---
- name: Backup Odoo databases on multiple servers
  hosts: all
  vars:
    backup_dir: /root/odoo_backups

  tasks:
    - name: Create backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory

    - name: Create Odoo database backup
      uri:
        url: "https://{{ odoo_domain }}/web/database/backup"
        method: POST
        return_content: yes
        body_format: form-multipart
        body:
          master_pwd: "{{ admin_password }}"
          name: "{{ odoo_database }}"
          backup_format: zip
      register: backup_response

    - name: Save the backup file
      copy:
        content: "{{ backup_response.content }}"
        dest: "{{ backup_dir }}/{{ odoo_database }}_{{ lookup('pipe', 'date +%F_%H-%M-%S') }}.zip"

    - name: Delete old backups
      find:
        paths: "{{ backup_dir }}"
        patterns: "{{ odoo_database }}_*.zip"
        age: 7d
        recurse: yes
      register: old_backups

    - name: Remove old backups
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_backups.files }}"
      when: old_backups.matched > 0
