- name: Update Servers
  hosts: all
  become: yes  # Run tasks with elevated privileges

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Upgrade all packages
      package:
        name: '*'
        state: latest
      when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'
